select 
HOST_NAME,
t.TABSCHEMA,
t.TABNAME,
t.card QTDA_LINHAS,
t.colcount QTDA_COLUNAS,
c.COLNAME,
C.TYPENAME,
C.LENGTH,
C.SCALE,
C.NULLS,
CASE WHEN R.FKCOLUMN_NAME IS NOT NULL then '1' ELSE '0' END AS IS_FK_COLUMN,
t.lastused,
t.REMARKS TABLE_COMENT,
c.REMARKS COLUMN_COMENTS,
SUM(A.DATA_OBJECT_P_SIZE)+SUM(INDEX_OBJECT_P_SIZE)+ SUM(LONG_OBJECT_P_SIZE)+SUM(LOB_OBJECT_P_SIZE)+ SUM(XML_OBJECT_P_SIZE)  as TAMANHO
from syscat.TABLES t
join syscat.columns c on t.TABSCHEMA=c.TABSCHEMA and t.TABNAME = c.TABNAME
join SYSIBMADM.ADMINTABINFO a on A.tabschema=t.tabschema and A.tabname=t.tabname
left join sysibm.SQLFOREIGNKEYS R on C.TABSCHEMA=R.FKTABLE_SCHEM and C.tabname=R.FKTABLE_NAME and C.colname=R.FKCOLUMN_NAME
cross join TABLE(SYSPROC.ENV_GET_SYS_INFO()) s
where t.tabschema not like 'SYS%'
group by s.HOST_NAME,t.TABSCHEMA,t.TABNAME,t.card,t.colcount,c.COLNAME,C.TYPENAME,
C.LENGTH,C.SCALE,C.NULLS,R.FKCOLUMN_NAME,t.lastused,t.REMARKS,c.REMARKS
